version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      # Disable unsafeptr check for CGO/FFI code
      disable:
        - unsafeptr
