/* Charybdis FFI - Generated by cbindgen. Do not edit. */

#ifndef CHARYBDIS_H
#define CHARYBDIS_H

/* Warning: this file is auto-generated. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque session handle
 */
typedef struct CharybdisSession CharybdisSession;

/**
 * Progress callback function pointer type.
 * Called with JSON-encoded ProgressEvent and user-provided data pointer.
 * Pass NULL to disable progress updates.
 */
typedef void (*CharybdisProgressCallback)(const char *json, void *user_data);

/**
 * Free a string allocated by charybdis
 */
 void charybdis_free_string(char *s);

/**
 * Get charybdis version
 */
 char *charybdis_version(void);

/**
 * Create a new benchmark session
 *
 * Returns NULL on error. Use `charybdis_last_error` to get error message.
 */
 struct CharybdisSession *charybdis_session_new(const char *config_json, const char *workload_json);

/**
 * Get session ID
 */
 char *charybdis_session_id(const struct CharybdisSession *session);

/**
 * Run the benchmark with progress callback
 *
 * Returns JSON results string or NULL on error.
 */

char *charybdis_session_run(struct CharybdisSession *session,
                            CharybdisProgressCallback callback,
                            void *user_data);

/**
 * Cancel a running benchmark
 */
 void charybdis_session_cancel(struct CharybdisSession *session);

/**
 * Free a session
 */
 void charybdis_session_free(struct CharybdisSession *session);

/**
 * Validate a Rune script
 *
 * Returns NULL if valid, or JSON error array if invalid.
 * The JSON array contains objects with: line, column, message, severity
 */
 char *charybdis_validate_script(const char *script);

/**
 * Get built-in workload templates as JSON
 */
 char *charybdis_builtin_workloads(void);

#endif  /* CHARYBDIS_H */
